"""Generate rtl/ble_gauss_lut.v from the golden model.

The Gaussian filter spans 3 symbols, so the output sample at phase j of
symbol n depends on 4 symbols: n-2..n+1 for j < SPS/2, n-1..n+2 otherwise.
Each symbol is +1, -1, or 0 (outside the packet, matching the zero padding of
np.convolve(mode="same") in the model). The LUT holds the model's quantized
fine code for every (phase, 4-symbol window), computed with the model's own
functions so the RTL matches it bit for bit.

Usage: python gen_gauss_lut.py [--step-hz 20000] [--sps 2 16]
"""

import argparse
import itertools
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "model"))

from ble_adv import DEVIATION_HZ, fine_codes, gaussian_taps  # noqa: E402

# Symbol encodings in the RTL window: {valid, bit}
SYM_CODE = {0: 0b00, -1: 0b10, +1: 0b11}


def lut_value(sps, j, window, step_hz):
    """Fine code for phase j given 5 symbols at offsets -2..+2 (n at index 2)."""
    nrz = np.repeat(np.asarray(window, dtype=float), sps)
    conv = np.convolve(nrz, gaussian_taps(sps), mode="same")
    f = DEVIATION_HZ * conv
    return int(fine_codes(f, step_hz)[2 * sps + j]), f[2 * sps + j] / step_hz


def check_span(sps):
    """Confirm each phase only reaches the 4 symbols the RTL selects."""
    half = len(gaussian_taps(sps)) // 2
    for j in range(sps):
        lo = (j - half) // sps
        hi = (j + half) // sps
        want = (-2, 1) if j < sps // 2 else (-1, 2)
        assert (lo, hi) == want, (sps, j, lo, hi)


def gen_module(sps, step_hz, width):
    check_span(sps)
    pw = max(1, (sps - 1).bit_length())
    lines = []
    worst_tie = 1.0
    lo, hi = 0, 0
    for j in range(sps):
        for w4 in itertools.product((-1, 0, 1), repeat=4):
            # Only contiguous packets are reachable: zeros only at the ends.
            s = "".join("x" if v else "0" for v in w4)
            if "x0x" in s or "x00x" in s:
                continue
            window = (list(w4) + [0]) if j < sps // 2 else ([0] + list(w4))
            code, raw = lut_value(sps, j, window, step_hz)
            if code == 0:
                continue
            worst_tie = min(worst_tie, abs(abs(raw - np.floor(raw)) - 0.5))
            lo, hi = min(lo, code), max(hi, code)
            key = (j << 8) | sum(SYM_CODE[v] << (2 * (3 - i)) for i, v in enumerate(w4))
            val = code & ((1 << width) - 1)
            lines.append(f"      {pw + 8}'h{key:0{(pw + 8 + 3) // 4}x}: code = {width}'h{val:0{(width + 3) // 4}x};  // j={j} {w4} -> {code}")
    assert -(1 << (width - 1)) <= lo and hi < (1 << (width - 1)), (lo, hi)
    body = "\n".join(lines)
    return (
        f"""
// SPS = {sps}, step = {step_hz:g} Hz, codes {lo}..{hi}, closest rounding tie {worst_tie:.3g} LSB
module ble_gauss_lut_sps{sps} (
  input  wire [{pw - 1}:0] phase,
  input  wire [7:0]  win,   // 4 symbols, oldest in [7:6], each {{valid, bit}}
  output reg  signed [{width - 1}:0] code
);
  always @* begin
    case ({{phase, win}})
{body}
      default: code = {width}'d0;
    endcase
  end
endmodule
""",
        lo,
        hi,
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--step-hz", type=float, default=20e3)
    ap.add_argument("--sps", type=int, nargs="+", default=[2, 16])
    ap.add_argument("--width", type=int, default=6)
    ap.add_argument("--out", default=os.path.join(HERE, "..", "rtl", "ble_gauss_lut.v"))
    a = ap.parse_args()
    mods = [gen_module(s, a.step_hz, a.width)[0] for s in a.sps]
    with open(a.out, "w") as fh:
        fh.write("// Generated by digital/scripts/gen_gauss_lut.py from model/ble_adv.py. Do not edit.\n")
        fh.write(f"// python gen_gauss_lut.py --step-hz {a.step_hz:g} --sps {' '.join(map(str, a.sps))} --width {a.width}\n")
        fh.write("`default_nettype none\n")
        fh.write("".join(mods))
        fh.write("`default_nettype wire\n")
    print(f"wrote {a.out}")


if __name__ == "__main__":
    main()
